version: '3'

networks:
  app-tier:
    driver: bridge

services:
  redis_app1:
    image: redis_app
    ports:
    - 8081:8080
    networks:
    - app-tier
  redis_app2:
    image: redis_app
    ports:
    - 8082:8080
    networks:
    - app-tier
  redis_app3:
    image: redis_app
    ports:
    - 8083:8080
    networks:
    - app-tier
  nginx:
    image: nginx:1.17.2-alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - redis_app1
    - redis_app2
    - redis_app3
    networks:
    - app-tier
   
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    restart: always
    volumes:
    - ./storage/redis/data:/data
    ports:
    - 6379:6379
